/*
 *  arImageProc.h
 *  ARToolKit6
 *
 *  This file is part of ARToolKit.
 *
 *  Copyright 2015-2016 Daqri, LLC.
 *  Copyright 2010-2015 ARToolworks, Inc.
 *
 *  Author(s): Philip Lamb
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

/*!
    @file arImageProc.h
    @brief   ARToolKit functions for 2D luminance image processing.
    @details
*/

#ifndef AR_IMAGEPROC_H
#define AR_IMAGEPROC_H

#ifndef TRUE
#  define TRUE 1
#endif
#ifndef FALSE
#  define FALSE 0
#endif

#include <AR6/AR/config.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __APPLE__
#  if !AR_DISABLE_THRESH_MODE_AUTO_ADAPTIVE
#    define AR_IMAGEPROC_USE_VIMAGE 1
#  endif
#endif

/*!
    @brief Structure holding settings for an instance of the image-processing pipeline.
 */
struct _ARImageProcInfo {
    unsigned char *__restrict image2;   ///< Extra buffer, allocated as required.
    int imageX;                         ///< Width of image buffer.
    int imageY;                         ///< Height of image buffer.
    unsigned long histBins[256];        ///< Luminance histogram.
    unsigned long cdfBins[256];         ///< Luminance cumulative density function.
    unsigned char min;                  ///< Minimum luminance.
    unsigned char max;                  ///< Maximum luminance.
#if AR_IMAGEPROC_USE_VIMAGE
    void *tempBuffer;                   ///< Extra buffer when using macOS/iOS vImage framework.
#endif
};
typedef struct _ARImageProcInfo ARImageProcInfo;
    
#ifdef __cplusplus
}
#endif

#include <AR6/AR/ar.h>

#ifdef __cplusplus
extern "C" {
#endif

/*!
    @brief Initialise image processing.
    @details
        This function creates the ARImageProcInfo structure required
        for other image processing functions. The size of the image
        that will be processed is fixed by this call.
    @param xsize Width of the images that will be processed, in pixels.
    @param ysize Height of the images that will be processed, in pixels.
    @result Pointer to the ARImageProcInfo structure. When processing
        is complete, this structure should be disposed of by calling
        arImageProcFinal.
    @see arImageProcFinal
 */
ARImageProcInfo *arImageProcInit(const int xsize, const int ysize);

/*!
    @brief Finish image processing and free memory.
    @details
        When processing is complete, the ARImageProcInfo structure should
        be disposed of by calling this function.
    @param ipi ARImageProcInfo structure to be disposed of, as created by arImageProcInit.
    @see arImageProcInit
 */
void arImageProcFinal(ARImageProcInfo *ipi);

/*!
    @brief Calculate luminance histogram.
    @param ipi ARImageProcInfo structure describing the format of the image
        to be processed, as created by arImageProcInit.
 
        On macOS and iOS, the calculation is accelerated using the Accelerate framework.
    @result 0 in case of success, or a value less than 0 in case of error.
 */
int arImageProcLumaHist(ARImageProcInfo *ipi, const ARUint8 *__restrict dataPtr);

/*!
    @brief Get luminance histogram as an image.
    @details 
        Returns a pointer to a buffer containing a 256x256 8-bit grayscale texture.
        The texture can be uploaded to an OpenGL texture with the calls:
        @code
            buf = arImageProcGetHistImage(ipi);
            if (buf) {
                glTexImage2D(GL_TEXTURE_2D, 0, GL_LUMINANCE, 256, 256, 0, GL_LUMINANCE, GL_UNSIGNED_BYTE, buf);
                free(buf);
            }
        @endcode
        After uploading, the texture can be drawn as with any other OpenGL texture.
    @param ipi ARImageProcInfo structure holding the most recently processed histogram,
        as generated by arImageProcLumaHist etc.
    @result Pointer to the texture data.
 */
unsigned char *arImageProcGetHistImage(ARImageProcInfo *ipi);

/*!
    @brief Calculate image histogram and cumulative density function.
    @param ipi ARImageProcInfo structure describing the format of the image
        to be processed, as created by arImageProcInit.
    @result 0 in case of success, or a value less than 0 in case of error.
 */
int arImageProcLumaHistAndCDF(ARImageProcInfo *ipi, const ARUint8 *__restrict dataPtr);

/*!
    @brief Calculate image histogram, cumulative density function, and luminance value at a given histogram percentile.
    @param ipi ARImageProcInfo structure describing the format of the image
        to be processed, as created by arImageProcInit.
    @result 0 in case of success, or a value less than 0 in case of error.
 */
int arImageProcLumaHistAndCDFAndPercentile(ARImageProcInfo *ipi, const ARUint8 *__restrict dataPtr, const float percentile, unsigned char *value_p);

/*!
    @brief Calculate image histogram, cumulative density function, and median luminance value.
    @param ipi ARImageProcInfo structure describing the format of the image
        to be processed, as created by arImageProcInit.
    @result 0 in case of success, or a value less than 0 in case of error.
 */
int arImageProcLumaHistAndCDFAndMedian(ARImageProcInfo *ipi, const ARUint8 *__restrict dataPtr, unsigned char *value_p);

/*!
    @brief Calculate image histogram, and binarize image using Otsu's method for foreground/background separation.
 
        See http://en.wikipedia.org/wiki/Otsu's_method fore more information.
    @param ipi ARImageProcInfo structure describing the format of the image
        to be processed, as created by arImageProcInit.
    @result 0 in case of success, or a value less than 0 in case of error.
 */
int arImageProcLumaHistAndOtsu(ARImageProcInfo *ipi, const ARUint8 *__restrict dataPtr, unsigned char *value_p);

/*!
    @brief Calculate image histogram, and box filter image.
    @details 
        See https://developer.apple.com/library/ios/documentation/Performance/Reference/vImage_convolution/
        On macOS and iOS, the calculation is accelerated using the Accelerate framework.
    @param ipi ARImageProcInfo structure describing the format of the image
        to be processed, as created by arImageProcInit.
    @result 0 in case of success, or a value less than 0 in case of error.
 */
#if !AR_DISABLE_THRESH_MODE_AUTO_ADAPTIVE
int arImageProcLumaHistAndBoxFilterWithBias(ARImageProcInfo *ipi, const ARUint8 *__restrict dataPtr, const int boxSize, const int bias);
#endif

/*!
    @brief Calculate image histogram, cumulative density function, and minimum and maximum luminance values.
    @param ipi ARImageProcInfo structure describing the format of the image
        to be processed, as created by arImageProcInit.
    @result 0 in case of success, or a value less than 0 in case of error.
 */
int arImageProcLumaHistAndCDFAndLevels(ARImageProcInfo *ipi, const ARUint8 *__restrict dataPtr);

#ifdef __cplusplus
}
#endif

#endif // !AR_IMAGEPROC_H
